export const hIndex = [
    {
        path: "/help/submit-a-log",
        title: "Submitting Your First Log",
        description: "Learn how to submit your first log on the logging software!",
        keywords: ["log", "logging", "first", "pota", "field day", "parks", "contacts", "contact"],
        category: "Getting Started",
    },
    {
        path: "/help/setup-your-operator",
        title: "Setup Your Operator",
        description: "Learn how to properly setup your operator using the operator modal!",
        keywords: ["operator", "setup", "pota", "field day", "parks", "log"],
        category: "Getting Started",
    },
    {
        path: "/help/editing-a-log",
        title: "Editing A Log You Submitted",
        description: "Learn how to edit a log you submitted!",
        keywords: ["log", "logging", "edit", "basics", "software", "editing"],
        category: "Getting Started",
    },
    {
        path: "/help/q-codes",
        title: "Q Codes",
        description: "Learn about Q codes, how they work, and what they are!",
        keywords: ["q", "qsl", "qrz", "qsy", "codes", "high frequency", "hf"],
        category: "Jargon",
    },
    {
        path: "/help/field-day",
        title: "What Is Field Day?",
        description: "Learn more about Field Day, Field Day requirements, and what the point of it is!",
        keywords: ["event", "events", "field day", "field", "day", "requirements", "operation", "operating"],
        category: "Amateur Radio Events",
    },
    {
        path: "/help/pota",
        title: "What Is POTA (Parks on the Air)?",
        description: "Learn more about POTA, POTA requirements, and what the point of it is!",
        keywords: ["event", "events", "parks", "on", "the", "air", "operating", "hf", "high frequency", "radio"],
        category: "Amateur Radio Events",
    },
    {
        path: "/help/overview-of-modes",
        title: "A Brief Overview of HF Modes",
        description: "Learn more about the different types of HF modes you can use!",
        keywords: ["hf", "modes", "FT8", "FT4", "RTTY", "data", "SSB", "voice", "digi"],
        category: "Getting Started",
    },
    {
        path: "/help/field-day-rules",
        title: "Field Day Rules",
        description: "Current Field Day Rules for the Upcoming Field Day Event",
        keywords: ["event", "events", "field day", "field", "day", "requirements", "operation", "operating", "rules"],
        category: "Event Documentation",
    },
    {
        path: "/help/pota-rules",
        title: "POTA Rules",
        description: "The Current Rules for POTA",
        keywords: ["event", "events", "POTA", "rules", "parks"],
        category: "Event Documentation",
    },
    {
        path: "/help/ft8",
        title: "What is FT8?",
        description: "Learn more about FT8, its use, and how to use it",
        keywords: ["digital", "modes", "ft8", "info", "contacts", "digi"],
        category: "Modes",
    },
    {
        path: "/help/ft4",
        title: "What is FT4?",
        description: "Learn more about FT4, its use, and how to use it",
        keywords: ["digital", "modes", "ft4", "info", "contacts", "digi"],
        category: "Modes",
    },
    {
        path: "/help/ssb",
        title: "What is SSB?",
        description: "Learn more about SSB, its use, and how to use it",
        keywords: ["analog", "SSB", "voice", "mode", "info", "contacts"],
        category: "Modes",
    },
    {
        path: "/help/rtty",
        title: "What is RTTY?",
        description: "Learn more about RTTY, its use, and how to use it",
        keywords: ["digital", "modes", "rtty", "info", "contacts", "digi"],
        category: "Modes",
    },
    {
        path: "/help/psk",
        title: "What is PSK?",
        description: "Learn more about PSK, its use, and how to use it",
        keywords: ["digital", "modes", "PSK", "info", "contacts", "digi"],
        category: "Modes",
    },
] // Uhhh it'll error for now.